// server.js

// 1. Setup Environment Variables and Dependencies
require('dotenv').config();
const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const { GoogleGenAI } = require('@google/genai'); // Note: Using the new SDK name

// Initialize Express App
const app = express();
const PORT = process.env.PORT || 3001;

// --- CONFIGURATION ---
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

if (!GEMINI_API_KEY) {
    console.error("FATAL ERROR: GEMINI_API_KEY is not defined in environment variables.");
    // Exit if the critical key is missing
    process.exit(1);
}

// Initialize the GoogleGenAI client
const ai = new GoogleGenAI(GEMINI_API_KEY);
// We are using the stable model you specified earlier
const model = ai.models.getGenerativeModel({ model: "gemini-2.5-flash" }); 

// --- MIDDLEWARE ---

// CORS: Allows the frontend (realcheck.netlify.app) to talk to this server (Render)
// Note: In production, you might want to restrict this to only your Netlify URL
app.use(cors()); 

// Body Parser: Configured for large image payloads (Base64 strings are large)
app.use(bodyParser.json({ limit: '50mb' }));
app.use(bodyParser.urlencoded({ limit: '50mb', extended: true }));


// --- HELPER FUNCTION ---

// Converts a Base64 string to a Google Generative Part object
function base64ToGenerativePart(base64Data, mimeType) {
    return {
        inlineData: {
            data: base64Data,
            mimeType
        }
    };
}


// --- API ROUTES ---

// Health Check Route
app.get('/', (req, res) => {
    res.status(200).send('RealCheck Backend is online and ready.');
});


// 2. The Main Analysis Route
app.post('/analyze', async (req, res) => {
    
    // 3. Input Validation and Preparation
    const { imageBase64 } = req.body;

    if (!imageBase64) {
        return res.status(400).json({ error: 'Missing imageBase64 in request body.' });
    }
    
    // The Base64 string typically includes a prefix (e.g., 'data:image/jpeg;base64,')
    const [header, data] = imageBase64.split(',');
    
    if (!data) {
        return res.status(400).json({ error: 'Invalid Base64 format.' });
    }

    // Attempt to parse the MIME type from the header
    const mimeMatch = header.match(/data:(.*?);/);
    const mimeType = mimeMatch ? mimeMatch[1] : 'image/jpeg'; // Default to jpeg if parsing fails

    try {
        const imagePart = base64ToGenerativePart(data, mimeType);

        // Define the prompt for AI image detection
        const prompt = `Analyze this image to determine if it was generated by Artificial Intelligence or captured by a human. Respond ONLY with a single JSON object that strictly matches this format:
        {
          "is_ai": boolean, 
          "confidence": number, // Confidence score (0-100)
          "reason": string // Detailed reasoning for your determination, focusing on artifacts, lighting, or lack of photographic realism.
        }`;

        // 4. Gemini API Call (THE FIX IS HERE)
        const response = await model.generateContent({
            contents: [imagePart, { text: prompt }],
            config: {
                responseMimeType: "application/json",
            }
        });

        // 🛑 FIX: response.text is a PROPERTY, not a function.
        // It holds the raw string content of the response.
        const responseText = response.text;

        // 5. Parse and Return Result
        let resultJson;
        try {
            // The responseText is a JSON string, so we parse it
            resultJson = JSON.parse(responseText.trim()); 
        } catch (e) {
            console.error("Failed to parse JSON response from Gemini:", responseText);
            // Return an error if the model fails to adhere to the requested JSON format
            return res.status(500).json({ 
                error: 'AI response was not valid JSON.',
                details: responseText
            });
        }

        // Return the parsed JSON object to the frontend
        res.status(200).json(resultJson);

    } catch (error) {
        console.error("Gemini API Error:", error);
        // Return a 500 status for any internal server/API failure
        res.status(500).json({ error: 'Internal Server Error', details: error.message });
    }
});


// --- START SERVER ---
app.listen(PORT, () => {
    console.log(`Server listening on port ${PORT}`);
});